### ISSUE TITLE
Sapling ABM

### ISSUE THREAD

**Issue by vlapsley** [duane-r/valleys_c#2]
Hi Duane,
I get the following error when the sapling ABM attempts to grow a tree:

`2016-04-03 11:46:41: ERROR[Main]: ServerError: Lua: Runtime error from mod 'valleys_c' in callback LuaABM::trigger(): ...sley/games/minetest/bin/../mods/valleys_c/deco_trees.lua:221: attempt to call a table value
`

Both banana and cherry blossom. 

Do not get the error with default:sapling though.

Thanks, demon_boy (Vaughan)

**Comment by duane-r** [comment]
R^2 code. OCG
